NODE('NODEJS') {
 STAGE('cHECKOUT') {
 GIT BRANCH: 'MAIN',
 URL: 'HTTPS://GITHUB.COM/your_github_user/DO400-PIPELINES-CONTROL'
 }
 STAGE('bACKEND tESTS') {
 SH 'NODE ./BACKEND/TEST.JS'
 }
 STAGE('fRONTEND tESTS') {SH 'NODE ./FRONTEND/TEST.JS'
 }
}

